### ISSUE TITLE
Version is 1.0.0 but latest tag is 0.5.0

### ISSUE THREAD

**Issue by rotu** [nim-lang/bigints#115]
Originally, reported in https://github.com/FedericoCeratto/nim-package-directory/issues/50, the package directory incorrectly lists this package as 0.5.0. As per [Nimble's documentation](https://github.com/nim-lang/nimble/blob/master/readme.markdown#versions), the version number needs to be bumped via git tag.

**Comment by dlesnoff** [comment]
@narimiran Could you bump the minor version with a git tag to 0.6.0 ? ([Git documentation about tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging), I guess an annotated tag is better )
See #117 users are confused since `nimble install bigints` installs a now very old version.

**Comment by rotu** [comment]
@dlesnoff the version is currently 1.0.0 https://github.com/nim-lang/bigints/blob/d843ecfe1e2a62c3b0e29d211df09763da408cac/bigints.nimble#L3

The cardinal rule of versioning is that numbers always go up. So I think the next tagged version should be >1.0.0, not 0.6.0

**Comment by Grench6** [comment]
@dlesnoff The existing tags are already lightweight, so I see no major benefit from changing to annotated tags.

I agree with @rotu: since all the old commits have version 1.0.0 on it, I think it would be better to increase it instead of decreasing it... its too late for that. Otherwise it will be even more confusing for people who is trying to understand the project history.

**Comment by narimiran** [comment]
`v1.0.0` tag pushed.

**Comment by rotu** [comment]
Confirmed the changes are reflected at https://nimble.directory/pkg/bigints
